const { ENV_API_BASE_URL, ENV_CLIENT_ID_THIRD_WEB, ENV_SECRET_KEY_THIRD_WEB } = import.meta.env

export const BASE_URL = ENV_API_BASE_URL
export const CLIENT_ID = ENV_CLIENT_ID_THIRD_WEB
export const SECRET_KEY = ENV_SECRET_KEY_THIRD_WEB
