const { VITE_API_BASE_URL, VITE_CLIENT_ID_THIRD_WEB, VITE_SECRET_KEY_THIRD_WEB } = import.meta.env

export const BASE_URL = VITE_API_BASE_URL
export const CLIENT_ID = VITE_CLIENT_ID_THIRD_WEB
export const SECRET_KEY = VITE_SECRET_KEY_THIRD_WEB
